from app.models.alert import COLLECTION as ALERTS_COLLECTION, INDEXES as ALERTS_INDEXES
from app.models.device import COLLECTION as DEVICES_COLLECTION, INDEXES as DEVICES_INDEXES
from app.models.distance_telemetry import COLLECTION as DISTANCE_COLLECTION, INDEXES as DISTANCE_INDEXES
from app.models.gps_log import COLLECTION as GPS_COLLECTION, INDEXES as GPS_INDEXES
from app.models.image_request import COLLECTION as IMAGE_REQUESTS_COLLECTION, INDEXES as IMAGE_REQUESTS_INDEXES
from app.models.installation_account import COLLECTION as INSTALLATION_ACCOUNTS_COLLECTION, INDEXES as INSTALLATION_ACCOUNTS_INDEXES
from app.models.installation_notification import COLLECTION as INSTALLATION_NOTIFICATIONS_COLLECTION, INDEXES as INSTALLATION_NOTIFICATIONS_INDEXES
from app.models.mobile_installation import COLLECTION as MOBILE_INSTALLATIONS_COLLECTION, INDEXES as MOBILE_INSTALLATIONS_INDEXES
from app.models.notification_event import COLLECTION as NOTIFICATION_EVENTS_COLLECTION, INDEXES as NOTIFICATION_EVENTS_INDEXES
from app.models.refresh_token import COLLECTION as REFRESH_TOKENS_COLLECTION, INDEXES as REFRESH_TOKENS_INDEXES
from app.models.user import COLLECTION as USERS_COLLECTION, INDEXES as USERS_INDEXES
from app.models.user_live_status import COLLECTION as LIVE_STATUS_COLLECTION, INDEXES as LIVE_STATUS_INDEXES
from app.models.vision_result import COLLECTION as VISION_RESULTS_COLLECTION, INDEXES as VISION_RESULTS_INDEXES

ACTIVE_COLLECTION_INDEXES: dict[str, list] = {
    USERS_COLLECTION: USERS_INDEXES,
    DEVICES_COLLECTION: DEVICES_INDEXES,
    GPS_COLLECTION: GPS_INDEXES,
    DISTANCE_COLLECTION: DISTANCE_INDEXES,
    IMAGE_REQUESTS_COLLECTION: IMAGE_REQUESTS_INDEXES,
    VISION_RESULTS_COLLECTION: VISION_RESULTS_INDEXES,
    ALERTS_COLLECTION: ALERTS_INDEXES,
    LIVE_STATUS_COLLECTION: LIVE_STATUS_INDEXES,
    REFRESH_TOKENS_COLLECTION: REFRESH_TOKENS_INDEXES,
    MOBILE_INSTALLATIONS_COLLECTION: MOBILE_INSTALLATIONS_INDEXES,
    INSTALLATION_ACCOUNTS_COLLECTION: INSTALLATION_ACCOUNTS_INDEXES,
    NOTIFICATION_EVENTS_COLLECTION: NOTIFICATION_EVENTS_INDEXES,
    INSTALLATION_NOTIFICATIONS_COLLECTION: INSTALLATION_NOTIFICATIONS_INDEXES,
}

LEGACY_COLLECTIONS = [
    "daily_alert_stats",
    "audit_logs",
    "alert_receivers",
    "notification_tokens",
    "follow_link_requests",
]
